spring:
  application:
      name: spring-ai-LLM

  ai:
    openai:
      api-key: key-from-openai-console

    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2:1b

    google:
      genai:
        api-key: key-from-google-cloud-console
        chat:
          options:
            model: gemini-2.5-flash

# ai:
#   anthropic:
#     api-key:

