spring:
  application:
    name: spring-ai-LLM

  ai:
    openai:
      api-key: xxxx

    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2:1b

    google:
      genai:
        api-key: xxxx
        chat:
          options:
            model: gemini-2.5-flash-lite

# ai:
#   anthropic:
#     api-key:

logging:
  level:
    org.springframework.ai.chat.memory: DEBUG
    org.springframework.ai.chat.client.advisor: DEBUG

